set(PICO_AXEL_URL_BASE "https://github.com/raspberrypi/pico-examples/tree/HEAD")
macro(axel_auto_set_url TARGET)
    file(RELATIVE_PATH URL_REL_PATH "${AXEL_PATH}" "${CMAKE_CURRENT_LIST_DIR}")
    pico_set_program_url(${TARGET} "${AXEL_URL_BASE}/${URL_REL_PATH}")
endmacro()
